name: Daily Cron Job

on:
  schedule:
    - cron: '45 13 * * *'  # Every day at midnight UTC

jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Change if you use a different version

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run your email-sending script
        run: python scraper2.py
